spring:
  application:
    name: mall-gateway
  cloud:
    gateway:
      routes: # 路由规则
        - id: baidu_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu #参数url=baidu
server:
  port: 88